# Generated by Django 5.1.2 on 2024-11-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
    ]
